/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedShippingRouteImport } from './routes/_authenticated/shipping'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedWorkspaceExecutiveRouteImport } from './routes/_authenticated/workspace.executive'
import { Route as AuthenticatedShippingShipmentIdRouteImport } from './routes/_authenticated/shipping.$shipmentId'
import { Route as AuthenticatedSettingsAuditLogsRouteImport } from './routes/_authenticated/settings.audit-logs'
import { Route as AuthenticatedSalesPipelineRouteImport } from './routes/_authenticated/sales.pipeline'
import { Route as AuthenticatedSalesOpportunitiesRouteImport } from './routes/_authenticated/sales.opportunities'
import { Route as AuthenticatedQuotationsQuotationIdRouteImport } from './routes/_authenticated/quotations.$quotationId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedInventoryProductsRouteImport } from './routes/_authenticated/inventory.products'
import { Route as AuthenticatedInventoryPricingRouteImport } from './routes/_authenticated/inventory.pricing'
import { Route as AuthenticatedCrmLeadsRouteImport } from './routes/_authenticated/crm.leads'
import { Route as AuthenticatedCrmCustomersRouteImport } from './routes/_authenticated/crm.customers'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedSalesOpportunitiesOpportunityIdRouteImport } from './routes/_authenticated/sales.opportunities.$opportunityId'
import { Route as AuthenticatedInventoryProductsProductIdRouteImport } from './routes/_authenticated/inventory.products.$productId'
import { Route as AuthenticatedCrmCustomersCustomerIdRouteImport } from './routes/_authenticated/crm.customers.$customerId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShippingRoute = AuthenticatedShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWorkspaceExecutiveRoute =
  AuthenticatedWorkspaceExecutiveRouteImport.update({
    id: '/executive',
    path: '/executive',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedShippingShipmentIdRoute =
  AuthenticatedShippingShipmentIdRouteImport.update({
    id: '/$shipmentId',
    path: '/$shipmentId',
    getParentRoute: () => AuthenticatedShippingRoute,
  } as any)
const AuthenticatedSettingsAuditLogsRoute =
  AuthenticatedSettingsAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSalesPipelineRoute =
  AuthenticatedSalesPipelineRouteImport.update({
    id: '/sales/pipeline',
    path: '/sales/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOpportunitiesRoute =
  AuthenticatedSalesOpportunitiesRouteImport.update({
    id: '/sales/opportunities',
    path: '/sales/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsQuotationIdRoute =
  AuthenticatedQuotationsQuotationIdRouteImport.update({
    id: '/$quotationId',
    path: '/$quotationId',
    getParentRoute: () => AuthenticatedQuotationsRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedInventoryProductsRoute =
  AuthenticatedInventoryProductsRouteImport.update({
    id: '/inventory/products',
    path: '/inventory/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryPricingRoute =
  AuthenticatedInventoryPricingRouteImport.update({
    id: '/inventory/pricing',
    path: '/inventory/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmLeadsRoute = AuthenticatedCrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmCustomersRoute =
  AuthenticatedCrmCustomersRouteImport.update({
    id: '/crm/customers',
    path: '/crm/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesOpportunitiesOpportunityIdRoute =
  AuthenticatedSalesOpportunitiesOpportunityIdRouteImport.update({
    id: '/$opportunityId',
    path: '/$opportunityId',
    getParentRoute: () => AuthenticatedSalesOpportunitiesRoute,
  } as any)
const AuthenticatedInventoryProductsProductIdRoute =
  AuthenticatedInventoryProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedInventoryProductsRoute,
  } as any)
const AuthenticatedCrmCustomersCustomerIdRoute =
  AuthenticatedCrmCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCrmCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai': typeof AuthenticatedAiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/shipping': typeof AuthenticatedShippingRouteWithChildren
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/crm/customers': typeof AuthenticatedCrmCustomersRouteWithChildren
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/inventory/pricing': typeof AuthenticatedInventoryPricingRoute
  '/inventory/products': typeof AuthenticatedInventoryProductsRouteWithChildren
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/sales/opportunities': typeof AuthenticatedSalesOpportunitiesRouteWithChildren
  '/sales/pipeline': typeof AuthenticatedSalesPipelineRoute
  '/settings/audit-logs': typeof AuthenticatedSettingsAuditLogsRoute
  '/shipping/$shipmentId': typeof AuthenticatedShippingShipmentIdRoute
  '/workspace/executive': typeof AuthenticatedWorkspaceExecutiveRoute
  '/crm/customers/$customerId': typeof AuthenticatedCrmCustomersCustomerIdRoute
  '/inventory/products/$productId': typeof AuthenticatedInventoryProductsProductIdRoute
  '/sales/opportunities/$opportunityId': typeof AuthenticatedSalesOpportunitiesOpportunityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai': typeof AuthenticatedAiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/shipping': typeof AuthenticatedShippingRouteWithChildren
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/crm/customers': typeof AuthenticatedCrmCustomersRouteWithChildren
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/inventory/pricing': typeof AuthenticatedInventoryPricingRoute
  '/inventory/products': typeof AuthenticatedInventoryProductsRouteWithChildren
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/sales/opportunities': typeof AuthenticatedSalesOpportunitiesRouteWithChildren
  '/sales/pipeline': typeof AuthenticatedSalesPipelineRoute
  '/settings/audit-logs': typeof AuthenticatedSettingsAuditLogsRoute
  '/shipping/$shipmentId': typeof AuthenticatedShippingShipmentIdRoute
  '/workspace/executive': typeof AuthenticatedWorkspaceExecutiveRoute
  '/crm/customers/$customerId': typeof AuthenticatedCrmCustomersCustomerIdRoute
  '/inventory/products/$productId': typeof AuthenticatedInventoryProductsProductIdRoute
  '/sales/opportunities/$opportunityId': typeof AuthenticatedSalesOpportunitiesOpportunityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/shipping': typeof AuthenticatedShippingRouteWithChildren
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/crm/customers': typeof AuthenticatedCrmCustomersRouteWithChildren
  '/_authenticated/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/_authenticated/inventory/pricing': typeof AuthenticatedInventoryPricingRoute
  '/_authenticated/inventory/products': typeof AuthenticatedInventoryProductsRouteWithChildren
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/_authenticated/sales/opportunities': typeof AuthenticatedSalesOpportunitiesRouteWithChildren
  '/_authenticated/sales/pipeline': typeof AuthenticatedSalesPipelineRoute
  '/_authenticated/settings/audit-logs': typeof AuthenticatedSettingsAuditLogsRoute
  '/_authenticated/shipping/$shipmentId': typeof AuthenticatedShippingShipmentIdRoute
  '/_authenticated/workspace/executive': typeof AuthenticatedWorkspaceExecutiveRoute
  '/_authenticated/crm/customers/$customerId': typeof AuthenticatedCrmCustomersCustomerIdRoute
  '/_authenticated/inventory/products/$productId': typeof AuthenticatedInventoryProductsProductIdRoute
  '/_authenticated/sales/opportunities/$opportunityId': typeof AuthenticatedSalesOpportunitiesOpportunityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai'
    | '/dashboard'
    | '/documents'
    | '/production'
    | '/projects'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/shipping'
    | '/workspace'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/crm/customers'
    | '/crm/leads'
    | '/inventory/pricing'
    | '/inventory/products'
    | '/projects/$projectId'
    | '/quotations/$quotationId'
    | '/sales/opportunities'
    | '/sales/pipeline'
    | '/settings/audit-logs'
    | '/shipping/$shipmentId'
    | '/workspace/executive'
    | '/crm/customers/$customerId'
    | '/inventory/products/$productId'
    | '/sales/opportunities/$opportunityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai'
    | '/dashboard'
    | '/documents'
    | '/production'
    | '/projects'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/shipping'
    | '/workspace'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/crm/customers'
    | '/crm/leads'
    | '/inventory/pricing'
    | '/inventory/products'
    | '/projects/$projectId'
    | '/quotations/$quotationId'
    | '/sales/opportunities'
    | '/sales/pipeline'
    | '/settings/audit-logs'
    | '/shipping/$shipmentId'
    | '/workspace/executive'
    | '/crm/customers/$customerId'
    | '/inventory/products/$productId'
    | '/sales/opportunities/$opportunityId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/ai'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/production'
    | '/_authenticated/projects'
    | '/_authenticated/quotations'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/shipping'
    | '/_authenticated/workspace'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/crm/customers'
    | '/_authenticated/crm/leads'
    | '/_authenticated/inventory/pricing'
    | '/_authenticated/inventory/products'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/quotations/$quotationId'
    | '/_authenticated/sales/opportunities'
    | '/_authenticated/sales/pipeline'
    | '/_authenticated/settings/audit-logs'
    | '/_authenticated/shipping/$shipmentId'
    | '/_authenticated/workspace/executive'
    | '/_authenticated/crm/customers/$customerId'
    | '/_authenticated/inventory/products/$productId'
    | '/_authenticated/sales/opportunities/$opportunityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipping': {
      id: '/_authenticated/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof AuthenticatedShippingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/executive': {
      id: '/_authenticated/workspace/executive'
      path: '/executive'
      fullPath: '/workspace/executive'
      preLoaderRoute: typeof AuthenticatedWorkspaceExecutiveRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/shipping/$shipmentId': {
      id: '/_authenticated/shipping/$shipmentId'
      path: '/$shipmentId'
      fullPath: '/shipping/$shipmentId'
      preLoaderRoute: typeof AuthenticatedShippingShipmentIdRouteImport
      parentRoute: typeof AuthenticatedShippingRoute
    }
    '/_authenticated/settings/audit-logs': {
      id: '/_authenticated/settings/audit-logs'
      path: '/audit-logs'
      fullPath: '/settings/audit-logs'
      preLoaderRoute: typeof AuthenticatedSettingsAuditLogsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/sales/pipeline': {
      id: '/_authenticated/sales/pipeline'
      path: '/sales/pipeline'
      fullPath: '/sales/pipeline'
      preLoaderRoute: typeof AuthenticatedSalesPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/opportunities': {
      id: '/_authenticated/sales/opportunities'
      path: '/sales/opportunities'
      fullPath: '/sales/opportunities'
      preLoaderRoute: typeof AuthenticatedSalesOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/$quotationId': {
      id: '/_authenticated/quotations/$quotationId'
      path: '/$quotationId'
      fullPath: '/quotations/$quotationId'
      preLoaderRoute: typeof AuthenticatedQuotationsQuotationIdRouteImport
      parentRoute: typeof AuthenticatedQuotationsRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/inventory/products': {
      id: '/_authenticated/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof AuthenticatedInventoryProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/pricing': {
      id: '/_authenticated/inventory/pricing'
      path: '/inventory/pricing'
      fullPath: '/inventory/pricing'
      preLoaderRoute: typeof AuthenticatedInventoryPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/leads': {
      id: '/_authenticated/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/customers': {
      id: '/_authenticated/crm/customers'
      path: '/crm/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof AuthenticatedCrmCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales/opportunities/$opportunityId': {
      id: '/_authenticated/sales/opportunities/$opportunityId'
      path: '/$opportunityId'
      fullPath: '/sales/opportunities/$opportunityId'
      preLoaderRoute: typeof AuthenticatedSalesOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof AuthenticatedSalesOpportunitiesRoute
    }
    '/_authenticated/inventory/products/$productId': {
      id: '/_authenticated/inventory/products/$productId'
      path: '/$productId'
      fullPath: '/inventory/products/$productId'
      preLoaderRoute: typeof AuthenticatedInventoryProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedInventoryProductsRoute
    }
    '/_authenticated/crm/customers/$customerId': {
      id: '/_authenticated/crm/customers/$customerId'
      path: '/$customerId'
      fullPath: '/crm/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCrmCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCrmCustomersRoute
    }
  }
}

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedQuotationsRouteChildren {
  AuthenticatedQuotationsQuotationIdRoute: typeof AuthenticatedQuotationsQuotationIdRoute
}

const AuthenticatedQuotationsRouteChildren: AuthenticatedQuotationsRouteChildren =
  {
    AuthenticatedQuotationsQuotationIdRoute:
      AuthenticatedQuotationsQuotationIdRoute,
  }

const AuthenticatedQuotationsRouteWithChildren =
  AuthenticatedQuotationsRoute._addFileChildren(
    AuthenticatedQuotationsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAuditLogsRoute: typeof AuthenticatedSettingsAuditLogsRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAuditLogsRoute: AuthenticatedSettingsAuditLogsRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedShippingRouteChildren {
  AuthenticatedShippingShipmentIdRoute: typeof AuthenticatedShippingShipmentIdRoute
}

const AuthenticatedShippingRouteChildren: AuthenticatedShippingRouteChildren = {
  AuthenticatedShippingShipmentIdRoute: AuthenticatedShippingShipmentIdRoute,
}

const AuthenticatedShippingRouteWithChildren =
  AuthenticatedShippingRoute._addFileChildren(
    AuthenticatedShippingRouteChildren,
  )

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceExecutiveRoute: typeof AuthenticatedWorkspaceExecutiveRoute
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceExecutiveRoute: AuthenticatedWorkspaceExecutiveRoute,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedCrmCustomersRouteChildren {
  AuthenticatedCrmCustomersCustomerIdRoute: typeof AuthenticatedCrmCustomersCustomerIdRoute
}

const AuthenticatedCrmCustomersRouteChildren: AuthenticatedCrmCustomersRouteChildren =
  {
    AuthenticatedCrmCustomersCustomerIdRoute:
      AuthenticatedCrmCustomersCustomerIdRoute,
  }

const AuthenticatedCrmCustomersRouteWithChildren =
  AuthenticatedCrmCustomersRoute._addFileChildren(
    AuthenticatedCrmCustomersRouteChildren,
  )

interface AuthenticatedInventoryProductsRouteChildren {
  AuthenticatedInventoryProductsProductIdRoute: typeof AuthenticatedInventoryProductsProductIdRoute
}

const AuthenticatedInventoryProductsRouteChildren: AuthenticatedInventoryProductsRouteChildren =
  {
    AuthenticatedInventoryProductsProductIdRoute:
      AuthenticatedInventoryProductsProductIdRoute,
  }

const AuthenticatedInventoryProductsRouteWithChildren =
  AuthenticatedInventoryProductsRoute._addFileChildren(
    AuthenticatedInventoryProductsRouteChildren,
  )

interface AuthenticatedSalesOpportunitiesRouteChildren {
  AuthenticatedSalesOpportunitiesOpportunityIdRoute: typeof AuthenticatedSalesOpportunitiesOpportunityIdRoute
}

const AuthenticatedSalesOpportunitiesRouteChildren: AuthenticatedSalesOpportunitiesRouteChildren =
  {
    AuthenticatedSalesOpportunitiesOpportunityIdRoute:
      AuthenticatedSalesOpportunitiesOpportunityIdRoute,
  }

const AuthenticatedSalesOpportunitiesRouteWithChildren =
  AuthenticatedSalesOpportunitiesRoute._addFileChildren(
    AuthenticatedSalesOpportunitiesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedShippingRoute: typeof AuthenticatedShippingRouteWithChildren
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
  AuthenticatedCrmCustomersRoute: typeof AuthenticatedCrmCustomersRouteWithChildren
  AuthenticatedCrmLeadsRoute: typeof AuthenticatedCrmLeadsRoute
  AuthenticatedInventoryPricingRoute: typeof AuthenticatedInventoryPricingRoute
  AuthenticatedInventoryProductsRoute: typeof AuthenticatedInventoryProductsRouteWithChildren
  AuthenticatedSalesOpportunitiesRoute: typeof AuthenticatedSalesOpportunitiesRouteWithChildren
  AuthenticatedSalesPipelineRoute: typeof AuthenticatedSalesPipelineRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedShippingRoute: AuthenticatedShippingRouteWithChildren,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
  AuthenticatedCrmCustomersRoute: AuthenticatedCrmCustomersRouteWithChildren,
  AuthenticatedCrmLeadsRoute: AuthenticatedCrmLeadsRoute,
  AuthenticatedInventoryPricingRoute: AuthenticatedInventoryPricingRoute,
  AuthenticatedInventoryProductsRoute:
    AuthenticatedInventoryProductsRouteWithChildren,
  AuthenticatedSalesOpportunitiesRoute:
    AuthenticatedSalesOpportunitiesRouteWithChildren,
  AuthenticatedSalesPipelineRoute: AuthenticatedSalesPipelineRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
