/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceExecutiveRouteImport } from './routes/workspace.executive'
import { Route as ShippingShipmentIdRouteImport } from './routes/shipping.$shipmentId'
import { Route as SalesPipelineRouteImport } from './routes/sales.pipeline'
import { Route as SalesOpportunitiesRouteImport } from './routes/sales.opportunities'
import { Route as QuotationsQuotationIdRouteImport } from './routes/quotations.$quotationId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as InventoryProductsRouteImport } from './routes/inventory.products'
import { Route as InventoryPricingRouteImport } from './routes/inventory.pricing'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmCustomersRouteImport } from './routes/crm.customers'
import { Route as SalesOpportunitiesOpportunityIdRouteImport } from './routes/sales.opportunities.$opportunityId'
import { Route as InventoryProductsProductIdRouteImport } from './routes/inventory.products.$productId'
import { Route as CrmCustomersCustomerIdRouteImport } from './routes/crm.customers.$customerId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceExecutiveRoute = WorkspaceExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => WorkspaceRoute,
} as any)
const ShippingShipmentIdRoute = ShippingShipmentIdRouteImport.update({
  id: '/$shipmentId',
  path: '/$shipmentId',
  getParentRoute: () => ShippingRoute,
} as any)
const SalesPipelineRoute = SalesPipelineRouteImport.update({
  id: '/sales/pipeline',
  path: '/sales/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOpportunitiesRoute = SalesOpportunitiesRouteImport.update({
  id: '/sales/opportunities',
  path: '/sales/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsQuotationIdRoute = QuotationsQuotationIdRouteImport.update({
  id: '/$quotationId',
  path: '/$quotationId',
  getParentRoute: () => QuotationsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const InventoryProductsRoute = InventoryProductsRouteImport.update({
  id: '/inventory/products',
  path: '/inventory/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryPricingRoute = InventoryPricingRouteImport.update({
  id: '/inventory/pricing',
  path: '/inventory/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCustomersRoute = CrmCustomersRouteImport.update({
  id: '/crm/customers',
  path: '/crm/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOpportunitiesOpportunityIdRoute =
  SalesOpportunitiesOpportunityIdRouteImport.update({
    id: '/$opportunityId',
    path: '/$opportunityId',
    getParentRoute: () => SalesOpportunitiesRoute,
  } as any)
const InventoryProductsProductIdRoute =
  InventoryProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => InventoryProductsRoute,
  } as any)
const CrmCustomersCustomerIdRoute = CrmCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CrmCustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/production': typeof ProductionRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quotations': typeof QuotationsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shipping': typeof ShippingRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/crm/customers': typeof CrmCustomersRouteWithChildren
  '/crm/leads': typeof CrmLeadsRoute
  '/inventory/pricing': typeof InventoryPricingRoute
  '/inventory/products': typeof InventoryProductsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/quotations/$quotationId': typeof QuotationsQuotationIdRoute
  '/sales/opportunities': typeof SalesOpportunitiesRouteWithChildren
  '/sales/pipeline': typeof SalesPipelineRoute
  '/shipping/$shipmentId': typeof ShippingShipmentIdRoute
  '/workspace/executive': typeof WorkspaceExecutiveRoute
  '/crm/customers/$customerId': typeof CrmCustomersCustomerIdRoute
  '/inventory/products/$productId': typeof InventoryProductsProductIdRoute
  '/sales/opportunities/$opportunityId': typeof SalesOpportunitiesOpportunityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/production': typeof ProductionRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quotations': typeof QuotationsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shipping': typeof ShippingRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/crm/customers': typeof CrmCustomersRouteWithChildren
  '/crm/leads': typeof CrmLeadsRoute
  '/inventory/pricing': typeof InventoryPricingRoute
  '/inventory/products': typeof InventoryProductsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/quotations/$quotationId': typeof QuotationsQuotationIdRoute
  '/sales/opportunities': typeof SalesOpportunitiesRouteWithChildren
  '/sales/pipeline': typeof SalesPipelineRoute
  '/shipping/$shipmentId': typeof ShippingShipmentIdRoute
  '/workspace/executive': typeof WorkspaceExecutiveRoute
  '/crm/customers/$customerId': typeof CrmCustomersCustomerIdRoute
  '/inventory/products/$productId': typeof InventoryProductsProductIdRoute
  '/sales/opportunities/$opportunityId': typeof SalesOpportunitiesOpportunityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/production': typeof ProductionRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quotations': typeof QuotationsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shipping': typeof ShippingRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/crm/customers': typeof CrmCustomersRouteWithChildren
  '/crm/leads': typeof CrmLeadsRoute
  '/inventory/pricing': typeof InventoryPricingRoute
  '/inventory/products': typeof InventoryProductsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/quotations/$quotationId': typeof QuotationsQuotationIdRoute
  '/sales/opportunities': typeof SalesOpportunitiesRouteWithChildren
  '/sales/pipeline': typeof SalesPipelineRoute
  '/shipping/$shipmentId': typeof ShippingShipmentIdRoute
  '/workspace/executive': typeof WorkspaceExecutiveRoute
  '/crm/customers/$customerId': typeof CrmCustomersCustomerIdRoute
  '/inventory/products/$productId': typeof InventoryProductsProductIdRoute
  '/sales/opportunities/$opportunityId': typeof SalesOpportunitiesOpportunityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/documents'
    | '/production'
    | '/projects'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/shipping'
    | '/workspace'
    | '/crm/customers'
    | '/crm/leads'
    | '/inventory/pricing'
    | '/inventory/products'
    | '/projects/$projectId'
    | '/quotations/$quotationId'
    | '/sales/opportunities'
    | '/sales/pipeline'
    | '/shipping/$shipmentId'
    | '/workspace/executive'
    | '/crm/customers/$customerId'
    | '/inventory/products/$productId'
    | '/sales/opportunities/$opportunityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/documents'
    | '/production'
    | '/projects'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/shipping'
    | '/workspace'
    | '/crm/customers'
    | '/crm/leads'
    | '/inventory/pricing'
    | '/inventory/products'
    | '/projects/$projectId'
    | '/quotations/$quotationId'
    | '/sales/opportunities'
    | '/sales/pipeline'
    | '/shipping/$shipmentId'
    | '/workspace/executive'
    | '/crm/customers/$customerId'
    | '/inventory/products/$productId'
    | '/sales/opportunities/$opportunityId'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/dashboard'
    | '/documents'
    | '/production'
    | '/projects'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/shipping'
    | '/workspace'
    | '/crm/customers'
    | '/crm/leads'
    | '/inventory/pricing'
    | '/inventory/products'
    | '/projects/$projectId'
    | '/quotations/$quotationId'
    | '/sales/opportunities'
    | '/sales/pipeline'
    | '/shipping/$shipmentId'
    | '/workspace/executive'
    | '/crm/customers/$customerId'
    | '/inventory/products/$productId'
    | '/sales/opportunities/$opportunityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  ProductionRoute: typeof ProductionRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  QuotationsRoute: typeof QuotationsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShippingRoute: typeof ShippingRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  CrmCustomersRoute: typeof CrmCustomersRouteWithChildren
  CrmLeadsRoute: typeof CrmLeadsRoute
  InventoryPricingRoute: typeof InventoryPricingRoute
  InventoryProductsRoute: typeof InventoryProductsRouteWithChildren
  SalesOpportunitiesRoute: typeof SalesOpportunitiesRouteWithChildren
  SalesPipelineRoute: typeof SalesPipelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/executive': {
      id: '/workspace/executive'
      path: '/executive'
      fullPath: '/workspace/executive'
      preLoaderRoute: typeof WorkspaceExecutiveRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/shipping/$shipmentId': {
      id: '/shipping/$shipmentId'
      path: '/$shipmentId'
      fullPath: '/shipping/$shipmentId'
      preLoaderRoute: typeof ShippingShipmentIdRouteImport
      parentRoute: typeof ShippingRoute
    }
    '/sales/pipeline': {
      id: '/sales/pipeline'
      path: '/sales/pipeline'
      fullPath: '/sales/pipeline'
      preLoaderRoute: typeof SalesPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/opportunities': {
      id: '/sales/opportunities'
      path: '/sales/opportunities'
      fullPath: '/sales/opportunities'
      preLoaderRoute: typeof SalesOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/$quotationId': {
      id: '/quotations/$quotationId'
      path: '/$quotationId'
      fullPath: '/quotations/$quotationId'
      preLoaderRoute: typeof QuotationsQuotationIdRouteImport
      parentRoute: typeof QuotationsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/inventory/products': {
      id: '/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof InventoryProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/pricing': {
      id: '/inventory/pricing'
      path: '/inventory/pricing'
      fullPath: '/inventory/pricing'
      preLoaderRoute: typeof InventoryPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/customers': {
      id: '/crm/customers'
      path: '/crm/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof CrmCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/opportunities/$opportunityId': {
      id: '/sales/opportunities/$opportunityId'
      path: '/$opportunityId'
      fullPath: '/sales/opportunities/$opportunityId'
      preLoaderRoute: typeof SalesOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof SalesOpportunitiesRoute
    }
    '/inventory/products/$productId': {
      id: '/inventory/products/$productId'
      path: '/$productId'
      fullPath: '/inventory/products/$productId'
      preLoaderRoute: typeof InventoryProductsProductIdRouteImport
      parentRoute: typeof InventoryProductsRoute
    }
    '/crm/customers/$customerId': {
      id: '/crm/customers/$customerId'
      path: '/$customerId'
      fullPath: '/crm/customers/$customerId'
      preLoaderRoute: typeof CrmCustomersCustomerIdRouteImport
      parentRoute: typeof CrmCustomersRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface QuotationsRouteChildren {
  QuotationsQuotationIdRoute: typeof QuotationsQuotationIdRoute
}

const QuotationsRouteChildren: QuotationsRouteChildren = {
  QuotationsQuotationIdRoute: QuotationsQuotationIdRoute,
}

const QuotationsRouteWithChildren = QuotationsRoute._addFileChildren(
  QuotationsRouteChildren,
)

interface ShippingRouteChildren {
  ShippingShipmentIdRoute: typeof ShippingShipmentIdRoute
}

const ShippingRouteChildren: ShippingRouteChildren = {
  ShippingShipmentIdRoute: ShippingShipmentIdRoute,
}

const ShippingRouteWithChildren = ShippingRoute._addFileChildren(
  ShippingRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceExecutiveRoute: typeof WorkspaceExecutiveRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceExecutiveRoute: WorkspaceExecutiveRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface CrmCustomersRouteChildren {
  CrmCustomersCustomerIdRoute: typeof CrmCustomersCustomerIdRoute
}

const CrmCustomersRouteChildren: CrmCustomersRouteChildren = {
  CrmCustomersCustomerIdRoute: CrmCustomersCustomerIdRoute,
}

const CrmCustomersRouteWithChildren = CrmCustomersRoute._addFileChildren(
  CrmCustomersRouteChildren,
)

interface InventoryProductsRouteChildren {
  InventoryProductsProductIdRoute: typeof InventoryProductsProductIdRoute
}

const InventoryProductsRouteChildren: InventoryProductsRouteChildren = {
  InventoryProductsProductIdRoute: InventoryProductsProductIdRoute,
}

const InventoryProductsRouteWithChildren =
  InventoryProductsRoute._addFileChildren(InventoryProductsRouteChildren)

interface SalesOpportunitiesRouteChildren {
  SalesOpportunitiesOpportunityIdRoute: typeof SalesOpportunitiesOpportunityIdRoute
}

const SalesOpportunitiesRouteChildren: SalesOpportunitiesRouteChildren = {
  SalesOpportunitiesOpportunityIdRoute: SalesOpportunitiesOpportunityIdRoute,
}

const SalesOpportunitiesRouteWithChildren =
  SalesOpportunitiesRoute._addFileChildren(SalesOpportunitiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  ProductionRoute: ProductionRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  QuotationsRoute: QuotationsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ShippingRoute: ShippingRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  CrmCustomersRoute: CrmCustomersRouteWithChildren,
  CrmLeadsRoute: CrmLeadsRoute,
  InventoryPricingRoute: InventoryPricingRoute,
  InventoryProductsRoute: InventoryProductsRouteWithChildren,
  SalesOpportunitiesRoute: SalesOpportunitiesRouteWithChildren,
  SalesPipelineRoute: SalesPipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
